---
- name: Install Docker
  hosts: all

  roles:
    - docker

- name: Configure Managers
  hosts: docker_swarm_manager

  roles:
    - manager

- name: Configure Workers
  hosts: docker_swarm_worker

  roles:
    - worker
