---
- name: Verifica se o Docker Swarm está habilitado.
  shell: docker info
  changed_when: False
  register: docker_info

- name: Pega o token do worker.
  shell: docker swarm join-token -q worker
  changed_when: False
  register: docker_worker_token
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  when: "docker_info.stdout.find('Swarm: active') == -1"

- name: Adiciona o servidor de Worker no cluster.
  shell: docker swarm join --token "{{ docker_worker_token.stdout }}" {{ docker_swarm_manager_ip }}:{{ docker_swarm_manager_port }}
  changed_when: False
  when: "docker_info.stdout.find('Swarm: active') == -1
    and docker_info.stdout.find('Swarm: pending') == -1"
